# Site settings
title: "ONG LézArts Humanitaire"
description: "L'ONG LézArts humanitaire est une organisation non-gouvernementale laïque, dont l'objectif est de favoriser et mettre en oeuvre des projets à caractère social, économique et culturel."

emails:
  - ptk.baumann@gmail.com
  - ptk@pygmeeweb.com

baseurl: ""
url: "http://www.lezartshumanitaire.com/"

language: fr

logoImage: logo-lezarts-humanitaire-optim.svg
titleImage: titre-lezarts-humanitaire-optim.svg

google_analytics_tracking_id:

timezone: "Europe/Paris"

authors:
  - id: ptk
    prenom: Patrick
    nom: Baumann
    fonction: Président Lézarts Humanitaire France

  - id: admin
    prenom: David
    nom: Jacquel
    fonction: Administrateur du site



defaults:
  -
    scope:
      type: pages
      path: "pages"
    values:
      permalink: /:basename/
      layout: page
  -
    scope:
      type: posts
    values:
      layout: post

excerpt_separator: <!--more-->

sass:

  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  style: nested

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: true
  # parse markdown inside block-level HTML tag
  parse_block_html: true


exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .travis.yml
  - bower.json
  - Readme.md

include:
  - .nojekyll

# gems: [jekyll/responsive_image]

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 30

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 550  # [Required] How wide the resized image will be.
      quality: 40 # [Optional] Overrides default_quality for this size.
    - width: 470
    - width: 350
    - width: 250
    - width: 150
    - width: 50
      quality: 20

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: img

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: img/resized/%{dirname}/%{width}/%{basename}

  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  # extra_images:
  #   - assets/foo/bar.png
  #   - assets/bgs/*.png
  #   - assets/avatars/*.{jpeg,jpg}

# ++++++++++++++++++++++++++++++++++++ Lézarts Humanitaire +++++++++++++++++++++++++++++++++++++++
#                                      Specific setup

figure:

  normal:
    classes: "col-md-3 col-sm-3 col-xs-6"
    sizes: "(min-width:1200px) 300px, (min-width:992px) 230px, (min-width:768px) 180px, 50vw"

  figureLeft:
    classes: "col-sm-4 col-sm-offset-1"
    sizes: "(min-width:1200px) 50vw, (min-width:992px) 470px, (min-width:768px) 350px, 90vw"

  figureRight:
    classes: "col-sm-4"
    sizes: "(min-width:1200px) 50vw, (min-width:992px) 470px, (min-width:768px) 350px, 90vw"

rotation-classes:
  - rot0
  - rot4
  - rot2
  - rot1
  - rot3
  - rot2
  - rot4
  - rot0
  - rot2
  - tor3

# ++++++++++++++++++++++ admin view page setup +++++++++++++++++++++++
admin:
  doDebug : true
  content-types:
    pages:
      displayProps:
        - url
        - title
        - menu
        - weight
        - permalink
        - layout
        - dir
        - name
        - path
      noDisplayProps:
        - content

    posts:
      displayProps:
       - title
       - authors
       - date
       - slug
       - ext
       - tags

      noDisplayProps:
       - path
       - url
       - type
       - id
       - matieres
       - taille
       - prix
       - images
       - output
       - content
       - collection
       - excerpt
       - previous
       - next
       - draft
       - categories
       - layout
       - relative_path
       - permalink
